# Kind cluster configuration
# Creates a local K8s cluster for development
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: secureinfer
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      # API service
      - containerPort: 30080
        hostPort: 8000
        protocol: TCP
      # Metrics
      - containerPort: 30090
        hostPort: 9090
        protocol: TCP
  - role: worker
  - role: worker
